from datetime import timezone, timedelta
COL = timezone(timedelta(hours=-5))

RHYTHM_TICK_MINUTES = 15

IDLE_SESSION_MINUTES = 30

MOOD_CHECK_MINUTES = 60

MOOD_IDLE_DECAY_MINUTES = 240

DAILY_MORNING_HOUR = 7
DAILY_MORNING_MINUTE = 0

NIGHTLY_QUIESCENCE_HOUR = 3
NIGHTLY_QUIESCENCE_MINUTE = 0

WEEKLY_FORGETTING_DAY = "mon"
WEEKLY_FORGETTING_HOUR = 4
WEEKLY_FORGETTING_MINUTE = 0